# Generated by Django 6.0.3 on 2026-03-18 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(choices=[('fund_6', '6º Ano - Fundamental'), ('fund_7', '7º Ano - Fundamental'), ('fund_8', '8º Ano - Fundamental'), ('fund_9', '9º Ano - Fundamental'), ('med_1', '1º Ano - Médio'), ('med_2', '2º Ano - Médio'), ('med_3', '3º Ano - Médio')], max_length=10, verbose_name='Série')),
                ('tipo', models.CharField(choices=[('regular', 'ensino regular'), ('tecnico', 'ensino Técnico')], max_length=10, verbose_name='Tipo de Ensino')),
                ('ano', models.IntegerField(verbose_name='Ano Letivo')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('numero_chamada', models.IntegerField(verbose_name='Número de Chamada')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='core.turma', verbose_name='Turma')),
            ],
        ),
    ]
