# Generated by Django 6.0.3 on 2026-03-18 01:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='numero_chamada',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de Chamada'),
        ),
    ]
