# Generated by Django 6.0.3 on 2026-03-18 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_aluno_numero_chamada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('indisciplina', 'Indisciplina'), ('briga', 'Briga'), ('desrespeito', 'Desrespeito'), ('outros', 'Outros')], max_length=20, verbose_name='Tipo')),
                ('gravidade', models.CharField(choices=[('leve', 'Leve'), ('moderado', 'Moderado'), ('grave', 'Grave')], max_length=10, verbose_name='Gravidade')),
                ('local', models.CharField(choices=[('dentro', 'Dentro da sala'), ('fora', 'Fora da sala')], max_length=10, verbose_name='Local')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('notificacao', models.BooleanField(default=False, verbose_name='Responsável Notificado')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='core.aluno', verbose_name='Aluno')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('turma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.turma', verbose_name='Turma')),
            ],
        ),
    ]
