# Generated by Django 6.0.3 on 2026-03-21 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ocorrencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Circulacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saida', models.DateTimeField(auto_now_add=True, verbose_name='Saída')),
                ('retorno', models.DateTimeField(blank=True, null=True, verbose_name='Retorno')),
                ('alerta_enviado', models.BooleanField(default=False, verbose_name='Alerta Enviado')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circulacoes', to='core.aluno', verbose_name='Aluno')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('presente', models.BooleanField(default=True, verbose_name='Present')),
                ('justificativa', models.TextField(blank=True, null=True, verbose_name='Justificativa')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencia', to='core.aluno', verbose_name='Aluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.turma', verbose_name='Turma')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ocorrencia', 'Ocorrência Disciplinar'), ('falta', 'Falta'), ('atraso', 'Atraso'), ('matando_aula', 'Matando Aula'), ('acumulo_ocorrencias', 'Acúmulo de Ocorrências')], max_length=20, verbose_name='Tipo')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL, verbose_name='Destinatário')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('professor', 'Professor'), ('monitor', 'Monitor'), ('direcao', 'Direção'), ('responsavel', 'Responsável')], max_length=15, verbose_name='Tipo de Perfil')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
